### ISSUE TITLE
needs a release for QuickCheck 2.13+

### ISSUE THREAD

**Issue by simonmichael** [sw17ch/data-clist#20]
Thanks for this lib. I'm interested in #16 and brick and stackage, but here's a more focussed issue: are there any plans for a new release of data-clist compatible with QuickCheck 2.13, released in march ?

**Comment by simonmichael** [comment]
Related: #19.

**Comment by jeremyjh** [comment]
I merged that PR and published it to Hackage as data-clist-0.1.2.3.

Sorry for the delay on this. We really need to find another maintainer for this library. I haven't used it since 2016, and barely use Haskell anymore. I'm not sure who added it to stackage, but whoever cares about this dependency tree on Stackage should ideally step up and maintain this package too.

**Comment by simonmichael** [comment]
Thank you! I bothered you since you're still listed as maintainer on hackage (and seemed more recently active than John). Now that the hackage release is compatible with current versions of deps, updating in stackage is easy; I'll submit a PR for that.
